# -*- coding: utf-8 -*-
"""TPintegradorFlaskLarisa-Len.Ropaselectornb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCt6WwJYmhWki9xcTTFrQlYVb-o5yaI-
"""

from flask import Flask, render_template, request

app = Flask(__name__)

temperatura = int(request.form["temperatura"])
llueve = request.form["llueve"]

def dar_consejo (temperatura, llueve):
    if temperatura < 10:
        consejo = "Hace frío, usa abrigo."
    elif temperatura <= 24:
        consejo = "La temperatura es agradable, usá ropa cómoda."
    else:
        consejo = "Hace calor, usa ropa ligera."

    if llueve == "s":
        consejo += " No olvides llevar paraguas."

    return consejo

@app.route("/", methods=["GET", "POST"])
def inicio():
    consejo = ""

    if request.method == "POST":
        temperatura = int(request.form["temperatura"])
        llueve = request.form["llueve"]

        consejo = dar_consejo(temperatura, llueve)

    return render_template("index.html", consejo=consejo)

if __name__ == "__main__":
    app.run(debug=True)